"""
ZIP Bundler
Creates downloadable ZIP packages with HTML report, CSV, and all images.
"""
import os
import zipfile
from pathlib import Path
from typing import List, Dict, Any

def create_results_bundle(
    html_path: str,
    csv_path: str,
    image_paths: List[str],
    output_zip_path: str,
    job_id: str
) -> str:
    """
    Create a ZIP bundle containing HTML report, CSV, and all images.

    Args:
        html_path: Path to HTML report (optional, None for large batches)
        csv_path: Path to results CSV
        image_paths: List of image file paths to include
        output_zip_path: Where to save the ZIP file
        job_id: Job identifier for organizing files

    Returns:
        Path to the created ZIP file
    """

    with zipfile.ZipFile(output_zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Add HTML report (at root level for easy access) - only if provided
        if html_path and os.path.exists(html_path):
            zipf.write(html_path, f'Report_{job_id}.html')

        # Add CSV (at root level)
        if csv_path and os.path.exists(csv_path):
            zipf.write(csv_path, f'results_{job_id}.csv')

        # Create images folder structure
        original_images = []
        result_images = []

        for img_path in image_paths:
            if not os.path.exists(img_path):
                continue

            filename = os.path.basename(img_path)

            # Organize by type
            if 'original' in filename.lower():
                original_images.append(img_path)
            else:
                result_images.append(img_path)

        # Add original images to images/original/
        for img_path in original_images:
            filename = os.path.basename(img_path)
            zipf.write(img_path, f'images/original/{filename}')

        # Add result images to images/detections/
        for img_path in result_images:
            filename = os.path.basename(img_path)
            zipf.write(img_path, f'images/detections/{filename}')

        # Add a README file explaining the contents
        has_html = html_path and os.path.exists(html_path)

        readme_content = f"""Building Analysis Results - Job {job_id}
{'=' * 60}

This package contains the complete results from your building analysis.

Contents:
---------"""

        if has_html:
            readme_content += f"""
1. Report_{job_id}.html
   - Open this file in any web browser
   - Self-contained with all images embedded
   - Perfect for sharing or archiving

2. results_{job_id}.csv"""
        else:
            readme_content += f"""
1. results_{job_id}.csv (HTML report not included for large batches)"""

        readme_content += """
   - Spreadsheet-compatible format
   - Contains addresses, detection status, confidence scores, and clickable image URLs
   - Copy-paste directly into Google Sheets for easy verification

"""

        if has_html:
            readme_content += "3. images/original/\n"
        else:
            readme_content += "2. images/original/\n"

        readme_content += """   - Original satellite images (768x768px)
   - Source: Mapbox Satellite (© Maxar)

"""

        if has_html:
            readme_content += "4. images/detections/\n"
        else:
            readme_content += "3. images/detections/\n"

        readme_content += """   - Annotated images showing detected cooling towers
   - Bounding boxes with confidence scores
   - Green "TARGET ZONE" box shows analyzed area
   - Generated by YOLOv8 model

Recommended Workflow:
--------------------"""

        if has_html:
            readme_content += f"""
- Quick review: Open Report_{job_id}.html in your browser"""

        readme_content += """
- Working in Google Sheets:
  1. Open results_{job_id}.csv in any text editor or Excel
  2. Select all (Ctrl+A), copy (Ctrl+C)
  3. Paste into Google Sheets
  4. Click image URLs in the sheet to verify detections
  5. Add your own columns for notes, status, follow-ups, etc.

- For permanent storage:
  1. Upload images/ folder to your Google Drive
  2. Share folder with "Anyone with link can view"
  3. Optional: Replace URLs in sheet with Drive URLs (for permanence)

- Archive: Keep this ZIP for offline backup and reference

Attribution:
------------
Imagery: © Maxar (via Mapbox)
Map Data: © OpenStreetMap contributors
ML Framework: Ultralytics YOLO (AGPL-3.0)
Built for: Parity, Inc.
"""

        zipf.writestr('README.txt', readme_content)

    return output_zip_path

def extract_image_paths_from_results(
    web_results: List[Dict[str, Any]],
    get_local_path_func
) -> List[str]:
    """
    Extract all local image paths from web_results.

    Args:
        web_results: List of result dictionaries
        get_local_path_func: Function to convert blob paths to local paths

    Returns:
        List of local file paths
    """
    image_paths = []

    for result in web_results:
        # Skip errors
        if result.get('error'):
            # Even errors might have original images
            original_url = result.get('original_image_url', '')
            if original_url.startswith('/files/'):
                blob = original_url.replace('/files/', '')
                local_path = str(get_local_path_func(blob))
                if os.path.exists(local_path):
                    image_paths.append(local_path)
            continue

        # Extract image URLs
        original_url = result.get('original_image_url', '')
        result_url = result.get('result_image_url', '')

        # Convert to local paths
        if original_url.startswith('/files/'):
            blob = original_url.replace('/files/', '')
            local_path = str(get_local_path_func(blob))
            if os.path.exists(local_path):
                image_paths.append(local_path)

        if result_url.startswith('/files/'):
            blob = result_url.replace('/files/', '')
            local_path = str(get_local_path_func(blob))
            if os.path.exists(local_path):
                image_paths.append(local_path)

    return image_paths
